### PR TITLE
Fixed errors in silly in discord error log

### PR DESCRIPTION
**Pull request by tayler6000**
Fixed https://discord.com/channels/677546901339504640/1017527224540344380/1025794344109740032

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I'm curious about the silly errors but appear to not have access to that log.

**Review by Aprillion — APPROVED** [review]

**Comment by plexish** [comment]
> I'm curious about the silly errors but appear to not have access to that log.

I think it's in this channel? https://discord.com/channels/677546901339504640/1017527224540344380

**Comment by JeroenDeDauw** [comment]
Also no access to that one 
image

**Comment by plexish** [comment]
> Also no access to that one image

oh, huh, you didn't have the bot dev role. Fixed now.

**Pull request merged**
