### PR TITLE
new url for SemanticAnswers

### PR DESCRIPTION
**Pull request by Aprillion**
@ccstan99 mentioned in Discord we should update to the new version.

### CODE REVIEW

**Review by ccstan99 — APPROVED** [review]
LGTM

**Comment by ccstan99** [comment]
FYI, this will return all questions. Passing parameter `status=live` will only show canonical answers... unless we're OK with returning non-canonical and incomplete answers back to user?

**Comment by Aprillion** [comment]
@plexish ^^

**Comment by plexish** [comment]
For now just live is good, at some point having the non-live ones displayable would be good. Likely eventual workflow is:
User types new question
UI says "None of those match my question"
Clicking that returns the non-live questions (with a +1 option for prioritization, maybe linking to the WIP Gdocs with a sutable warning about not being ready) and a button to add new question as the current one is

**Pull request merged**
